//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneyBee.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POItem
    {
        public int POItemId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int ProduceId { get; set; }
        public Nullable<float> PriceOrdered { get; set; }
        public Nullable<float> PriceReceived { get; set; }
        public Nullable<float> QuantityOrdered { get; set; }
        public Nullable<float> QuantityReceived { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime RowVersion { get; set; }
    
        public virtual Produce produce { get; set; }
        public virtual PurchaseOrder purchaseorder { get; set; }
    }
}
