//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneyBee.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produce
    {
        public Produce()
        {
            this.poitems = new HashSet<POItem>();
            this.producelogs = new HashSet<ProduceLog>();
            this.soproduces = new HashSet<SOProduce>();
        }
    
        public int ProduceId { get; set; }
        public string ProduceNo { get; set; }
        public string BarCode { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public int CategoryId { get; set; }
        public string PackSize { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal FactoryPrice { get; set; }
        public string OrderSize { get; set; }
        public Nullable<decimal> PackFee { get; set; }
        public Nullable<decimal> ProcessFee { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public bool Enable { get; set; }
        public Nullable<sbyte> HowUsed { get; set; }
        public Nullable<sbyte> HowPurchased { get; set; }
        public Nullable<float> PurchasedUsedRatio { get; set; }
        public Nullable<System.DateTime> LastOrderDate { get; set; }
        public Nullable<float> ExpirationDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime RowVersion { get; set; }
    
        public virtual Category category { get; set; }
        public virtual ICollection<POItem> poitems { get; set; }
        public virtual ICollection<ProduceLog> producelogs { get; set; }
        public virtual ICollection<SOProduce> soproduces { get; set; }
    }
}
