//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneybee.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCard
    {
        public MemberCard()
        {
            this.MemberCardLogs = new HashSet<MemberCardLog>();
            this.UserMemberCards = new HashSet<UserMemberCard>();
        }
    
        public int MemberCardId { get; set; }
        public string MemberCardNo { get; set; }
        public string Name { get; set; }
        public sbyte MemberType { get; set; }
        public float MemberMoney { get; set; }
        public System.DateTime DispatchDate { get; set; }
        public Nullable<int> DispatchUser { get; set; }
        public float SurplusMoney { get; set; }
        public bool IsEnable { get; set; }
        public string PasswordSalt { get; set; }
        public string PasswordHash { get; set; }
        public sbyte MemberCardStatus { get; set; }
        public string Descript { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime RowVersion { get; set; }
    
        public virtual ICollection<MemberCardLog> MemberCardLogs { get; set; }
        public virtual ICollection<UserMemberCard> UserMemberCards { get; set; }
    }
}
