//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneybee.DataModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmallHoneybeeEntities : DbContext
    {
        public SmallHoneybeeEntities()
            : base("name=SmallHoneybeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<POItem> POItems { get; set; }
        public virtual DbSet<Produce> Produces { get; set; }
        public virtual DbSet<Producelog> Producelogs { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<SaleOrder> SaleOrders { get; set; }
        public virtual DbSet<SOLog> SOLogs { get; set; }
        public virtual DbSet<SOProduce> SOProduces { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Userlog> Userlogs { get; set; }
    }
}
