//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneybee.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produce
    {
        public Produce()
        {
            this.POItems = new HashSet<POItem>();
            this.Producelogs = new HashSet<Producelog>();
            this.SOProduces = new HashSet<SOProduce>();
        }
    
        public int ProduceId { get; set; }
        public string ProduceNo { get; set; }
        public string BarCode { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string PackSize { get; set; }
        public float RetailPrice { get; set; }
        public float DiscountRate { get; set; }
        public Nullable<float> LowestDiscountRate { get; set; }
        public float FactoryPrice { get; set; }
        public string OrderSize { get; set; }
        public Nullable<float> PackFee { get; set; }
        public Nullable<float> ProcessFee { get; set; }
        public string Description { get; set; }
        public float Quantity { get; set; }
        public bool Enable { get; set; }
        public Nullable<sbyte> HowUsed { get; set; }
        public Nullable<sbyte> HowPurchased { get; set; }
        public Nullable<float> PurchasedUsedRatio { get; set; }
        public Nullable<System.DateTime> LastOrderDate { get; set; }
        public Nullable<float> ExpirationDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime RowVersion { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<POItem> POItems { get; set; }
        public virtual ICollection<Producelog> Producelogs { get; set; }
        public virtual ICollection<SOProduce> SOProduces { get; set; }
    }
}
