//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneybee.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.POItems = new HashSet<POItem>();
        }
    
        public int PurchaseOrderId { get; set; }
        public string POContractNo { get; set; }
        public string PurchaseOrderNo { get; set; }
        public string Name { get; set; }
        public int OriginatorId { get; set; }
        public sbyte POStatusCategory { get; set; }
        public Nullable<System.DateTime> DateOriginated { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<float> TotalAmount { get; set; }
        public Nullable<float> TotalTax { get; set; }
        public Nullable<float> TotalShipping { get; set; }
        public Nullable<float> TotalOther { get; set; }
        public Nullable<float> GrandTotal { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime RowVersion { get; set; }
    
        public virtual ICollection<POItem> POItems { get; set; }
        public virtual User User { get; set; }
    }
}
