//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneybee.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        public SaleOrder()
        {
            this.SOLogs = new HashSet<SOLog>();
            this.SOProduces = new HashSet<SOProduce>();
        }
    
        public int SaleOrderId { get; set; }
        public string SaleOrderNo { get; set; }
        public string Name { get; set; }
        public sbyte SaleOrderStatus { get; set; }
        public Nullable<int> OriginUserId { get; set; }
        public Nullable<int> PurchaseOrderUserId { get; set; }
        public sbyte HowBalance { get; set; }
        public Nullable<System.DateTime> DateOriginated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<float> ProduceCost { get; set; }
        public Nullable<float> FavorableCost { get; set; }
        public Nullable<float> OtherCost { get; set; }
        public Nullable<float> TotalCost { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime RowVersion { get; set; }
        public Nullable<float> ProduceTotalCount { get; set; }
        public Nullable<float> ProduceTotalOriginal { get; set; }
        public Nullable<float> ProduceTotalDiscount { get; set; }
    
        public virtual User OriginUserUser { get; set; }
        public virtual User PrucahseOrderUserUser { get; set; }
        public virtual ICollection<SOLog> SOLogs { get; set; }
        public virtual ICollection<SOProduce> SOProduces { get; set; }
    }
}
