//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneybee.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOProduce
    {
        public int SOProduceId { get; set; }
        public int SaleOrderId { get; set; }
        public Nullable<int> ProduceId { get; set; }
        public float DiscountRate { get; set; }
        public Nullable<System.DateTime> DateSaled { get; set; }
        public Nullable<float> Quantity { get; set; }
        public Nullable<float> CostPerUnit { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime RowVersion { get; set; }
    
        public virtual Produce Produce { get; set; }
        public virtual SaleOrder SaleOrder { get; set; }
    }
}
