//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHoneybee.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.SaleOrdersOriginUser = new HashSet<SaleOrder>();
            this.SaleOrdersPurchaseOrderUser = new HashSet<SaleOrder>();
            this.Userlogs = new HashSet<Userlog>();
        }
    
        public int UserId { get; set; }
        public sbyte UserType { get; set; }
        public string UserNo { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string PasswordSalt { get; set; }
        public string PasswordHash { get; set; }
        public float CashBalance { get; set; }
        public float CashFee { get; set; }
        public float CashTotal { get; set; }
        public float MemberPoints { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Weichat { get; set; }
        public string QqNo { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime RowVersion { get; set; }
        public sbyte Sex { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<sbyte> MemberType { get; set; }
    
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<SaleOrder> SaleOrdersOriginUser { get; set; }
        public virtual ICollection<SaleOrder> SaleOrdersPurchaseOrderUser { get; set; }
        public virtual ICollection<Userlog> Userlogs { get; set; }
    }
}
